version: '3.8'

services:
  orientdb:
    image: kauahensilva/orientdb:2.2.37
    ports:
      - "2424:2424"
      - "2480:2480"
    environment:
      ORIENTDB_ROOT_PASSWORD: 'root'
    volumes:
      - /orientdb/config:/opt/orientdb/config
      - /orientdb/databases:/opt/orientdb/databases
      - /orientdb/backup:/opt/orientdb/backup
    restart: always


  # server:
  #   build:
  #     context: ./src  

  #   environment:
  #     - HOST=orientdb
  #     - PASSWORDBD=root
  #     - HOSTBD=root

  #   # Limita a quantidade de memória que o container pode utilizar
  #   mem_limit: 2g

