version: '3.9'

services:
  db:
    image: kauahensilva/orientdb:2.2.37
    ports:
      - "2424:2424"
      - "2480:2480"
    environment:
      ORIENTDB_ROOT_PASSWORD: 'root'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
<<<<<<< HEAD
    networks:
      - wifi_network

networks:
  wifi_network:
    external: true
=======
      placement:
        preferences:
          - spread: node.hostname

networks:
  project-network:
    driver: overlay
    ipam:
      config:
        - subnet: 10.180.41.0/24
>>>>>>> 6d085d6bc0bdc54b320d6f4984222d42f491d352
