services:

  db:
    restart: always
    image: orientdb:3.2.35
    ports:
      - "2424:2425"
      - "2480:2481"
    network_mode: "host"
    volumes:
      - /orentdb/config:/opt/orientdb/config
      - /orientdb/databases:/opt/orientdb/databases
      - /orientdb/backup:/opt/orientdb/backup
    environment:
      ORIENTDB_ROOT_PASSWORD: 'root'
    
    # deploy:
    #   replicas: 1
    #   restart_policy:
    #     condition: on-failure
    #   placement:
    #     preferences:
    #       - spread: node.hostname
          
  # server:
  #   build:
  #     context: ./src  

  #   environment:
  #     - HOST=orientdb
  #     - PASSWORDBD=root
  #     - HOSTBD=root

  #   # Limita a quantidade de memória que o container pode utilizar
  #   mem_limit: 2g